"""Docker Deployment Engine compiling container configurations."""

from __future__ import annotations

import time
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

from flock.deployment.models import DeploymentDefinition


class DockerRestartPolicy(str, Enum):
    """Enums representing container restart policies."""
    NO = "no"
    ALWAYS = "always"
    ON_FAILURE = "on-failure"
    UNLESS_STOPPED = "unless-stopped"


class DockerNetworkMode(str, Enum):
    """Enums representing container network modes."""
    BRIDGE = "bridge"
    HOST = "host"
    NONE = "none"
    CUSTOM = "custom"


class DockerHealthCheck(BaseModel):
    """Health check criteria specs."""
    test_command: List[str] = Field(default_factory=list)
    interval: int = 30  # seconds
    timeout: int = 30  # seconds
    retries: int = 3
    start_period: int = 0

    model_config = {"frozen": True}


class DockerVolumeConfig(BaseModel):
    """Volume binding mounting configuration."""
    source: str
    target: str
    read_only: bool = False
    is_named_volume: bool = False

    model_config = {"frozen": True}


class DockerNetworkConfig(BaseModel):
    """Port mappings and aliases network settings."""
    mode: DockerNetworkMode = DockerNetworkMode.BRIDGE
    aliases: List[str] = Field(default_factory=list)
    published_ports: Dict[int, int] = Field(default_factory=dict)  # host_port -> container_port

    model_config = {"frozen": True}


class DockerRuntimeConfig(BaseModel):
    """Execution resources boundaries limits."""
    cpu_limit: Optional[float] = None  # e.g. 0.5 CPUs
    memory_limit_mb: Optional[int] = None  # e.g. 512 MB
    memory_reservation_mb: Optional[int] = None
    read_only_rootfs: bool = False
    restart_policy: DockerRestartPolicy = DockerRestartPolicy.ALWAYS
    hostname: Optional[str] = None
    working_dir: str = "/app"
    user: Optional[str] = None

    model_config = {"frozen": True}


class DockerImage(BaseModel):
    """Docker image identifiers tags."""
    image_name: str
    tag: str = "latest"

    model_config = {"frozen": True}


class DockerContainer(BaseModel):
    """Container representation wrapping runtime settings."""
    container_name: str
    image: DockerImage
    runtime_config: DockerRuntimeConfig
    networks: List[DockerNetworkConfig] = Field(default_factory=list)
    volumes: List[DockerVolumeConfig] = Field(default_factory=list)
    env_vars: Dict[str, str] = Field(default_factory=dict)
    health_check: Optional[DockerHealthCheck] = None

    model_config = {"frozen": True}


class DockerfileGenerator:
    """Generates Dockerfiles deterministically from container specifications."""

    def generate_dockerfile(
        self,
        base_image: str = "python:3.11-slim",
        working_dir: str = "/app",
        requirements_path: Optional[str] = "requirements.txt",
        entrypoint: Optional[List[str]] = None,
        cmd: Optional[List[str]] = None,
        env_vars: Optional[Dict[str, str]] = None,
        ports: Optional[List[int]] = None,
        healthcheck: Optional[DockerHealthCheck] = None,
        labels: Optional[Dict[str, str]] = None,
    ) -> str:
        """Create deterministic Dockerfile content string."""
        lines = []
        lines.append(f"# Generated by Flock Docker Generator — 2026-07-26")
        lines.append(f"FROM {base_image}\n")
        lines.append(f"WORKDIR {working_dir}\n")

        if env_vars:
            for k, v in sorted(env_vars.items()):
                lines.append(f"ENV {k}={v}")
            lines.append("")

        if labels:
            for k, v in sorted(labels.items()):
                lines.append(f"LABEL {k}={v}")
            lines.append("")

        lines.append("# Copy requirements and install dependencies")
        if requirements_path:
            lines.append(f"COPY {requirements_path} .")
            lines.append("RUN pip install --no-cache-dir -r requirements.txt\n")

        lines.append("COPY . .\n")

        if ports:
            for p in sorted(ports):
                lines.append(f"EXPOSE {p}")
            lines.append("")

        if healthcheck and healthcheck.test_command:
            test_str = " ".join(healthcheck.test_command)
            lines.append(
                f"HEALTHCHECK --interval={healthcheck.interval}s --timeout={healthcheck.timeout}s --retries={healthcheck.retries} \\"
            )
            lines.append(f"  CMD {test_str}\n")

        if entrypoint:
            entry_str = ", ".join(f'"{x}"' for x in entrypoint)
            lines.append(f"ENTRYPOINT [{entry_str}]")

        if cmd:
            cmd_str = ", ".join(f'"{x}"' for x in cmd)
            lines.append(f"CMD [{cmd_str}]")

        return "\n".join(lines)


class DockerValidationResult(BaseModel):
    """Validation report mapping errors."""
    is_valid: bool
    errors: List[str] = Field(default_factory=list)

    model_config = {"frozen": True}


class DockerValidator:
    """Docker configurations constraint validator."""

    @staticmethod
    def validate_container(container: DockerContainer) -> DockerValidationResult:
        """Validate images name format, port ranges, and duplicate mounts."""
        errors = []
        
        # 1. Image name validation
        img = container.image.image_name
        if not img or len(img) < 2:
            errors.append(f"Invalid image name: '{img}'")

        # 2. Port range validation
        for net in container.networks:
            for host_port, container_port in net.published_ports.items():
                if host_port < 1 or host_port > 65535 or container_port < 1 or container_port > 65535:
                    errors.append(f"Invalid port mapping: {host_port}:{container_port}")

        # 3. Duplicate mount validation
        mounts = set()
        for vol in container.volumes:
            if vol.target in mounts:
                errors.append(f"Duplicate mount target detected: '{vol.target}'")
            mounts.add(vol.target)

        # 4. Memory limit validation
        cfg = container.runtime_config
        if cfg.memory_limit_mb and cfg.memory_reservation_mb:
            if cfg.memory_reservation_mb > cfg.memory_limit_mb:
                errors.append("Memory reservation cannot exceed memory limit.")

        return DockerValidationResult(
            is_valid=len(errors) == 0,
            errors=errors
        )


class DockerDeploymentEngine:
    """Compiles container configurations and docker compose overrides (Legacy)."""

    def __init__(self) -> None:
        pass

    def generate_compose_file(self, deployment: DeploymentDefinition) -> str:
        """Create docker compose file content string (Legacy endpoint)."""
        return f"""version: '3.8'
services:
  {deployment.name}:
    image: {deployment.image}
    environment:
      - FLOCK_NAMESPACE={deployment.namespace}
    deploy:
      replicas: {deployment.replicas}
"""


# ------------------------------------------------------------------
# Phase 3 — Docker Compose Orchestration Models
# ------------------------------------------------------------------

class ComposeDependsOn(BaseModel):
    """Configuration dependencies condition maps."""
    condition: str = "service_healthy"

    model_config = {"frozen": True}


class ComposeHealthCheck(BaseModel):
    """Compose service health checking options."""
    test: List[str] = Field(default_factory=list)
    interval: str = "30s"
    timeout: str = "30s"
    retries: int = 3
    start_period: str = "0s"

    model_config = {"frozen": True}


class ComposeService(BaseModel):
    """Individual service mapping spec coordinates."""
    container_name: str
    image: str
    build: Optional[str] = None
    ports: List[str] = Field(default_factory=list)
    volumes: List[str] = Field(default_factory=list)
    networks: List[str] = Field(default_factory=list)
    environment: Dict[str, str] = Field(default_factory=dict)
    depends_on: Dict[str, ComposeDependsOn] = Field(default_factory=dict)
    healthcheck: Optional[ComposeHealthCheck] = None
    cpu_limit: Optional[str] = None
    memory_limit: Optional[str] = None
    restart: str = "always"

    model_config = {"frozen": True}


class ComposeNetwork(BaseModel):
    """Compose custom overlay driver maps."""
    driver: str = "bridge"

    model_config = {"frozen": True}


class ComposeVolume(BaseModel):
    """Compose custom persistence volume maps."""
    driver: str = "local"

    model_config = {"frozen": True}


class ComposeProject(BaseModel):
    """Multi-service compose blueprint container."""
    version: str = "3.8"
    services: Dict[str, ComposeService] = Field(default_factory=dict)
    networks: Dict[str, ComposeNetwork] = Field(default_factory=dict)
    volumes: Dict[str, ComposeVolume] = Field(default_factory=dict)

    model_config = {"frozen": True}


# ------------------------------------------------------------------
# Deterministic YAML Serialization
# ------------------------------------------------------------------

def to_yaml(data: Dict[str, Any] | List[Any] | str | int | float | bool, indent: int = 0) -> str:
    """Format inputs dictionary into sorted, deterministic YAML string."""
    lines: List[str] = []
    if isinstance(data, dict):
        for k in sorted(data.keys()):
            v = data[k]
            if v is None:
                continue
            if isinstance(v, (dict, list)):
                lines.append(f"{' ' * indent}{k}:")
                sub = to_yaml(v, indent + 2)
                if sub:
                    lines.append(sub)
            else:
                if isinstance(v, bool):
                    v_str = "true" if v else "false"
                else:
                    v_str = str(v)
                lines.append(f"{' ' * indent}{k}: {v_str}")
    elif isinstance(data, list):
        for item in data:
            if isinstance(item, (dict, list)):
                item_lines = to_yaml(item, indent + 2).split("\n")
                if item_lines:
                    first_line = item_lines[0].lstrip()
                    lines.append(f"{' ' * indent}- {first_line}")
                    for extra in item_lines[1:]:
                        lines.append(extra)
            else:
                lines.append(f"{' ' * indent}- {item}")
    return "\n".join(lines)


class ComposeEngine:
    """Orchestration compiler generating deterministic docker-compose YAMLs."""

    def generate_compose(self, project: ComposeProject) -> str:
        """Serialize ComposeProject model into clean YAML format."""
        return to_yaml(project.model_dump())

    def generate_cluster_compose(
        self,
        cluster_name: str,
        replicas: int = 3,
        image: str = "flock-node:latest",
        ports_start: int = 8080,
    ) -> ComposeProject:
        """Build ready-to-run multi-node ComposeProject specifications."""
        services: Dict[str, ComposeService] = {}
        networks = {"flock-mesh": ComposeNetwork()}
        volumes = {"flock-data": ComposeVolume()}

        # Coordinator
        coord_name = f"{cluster_name}-coordinator"
        services[coord_name] = ComposeService(
            container_name=coord_name,
            image=image,
            ports=[f"{ports_start}:{ports_start}"],
            volumes=["flock-data:/var/flock"],
            networks=["flock-mesh"],
            environment={"FLOCK_ROLE": "coordinator", "FLOCK_NODE_ID": coord_name},
            restart="always",
        )

        # Workers
        for i in range(1, replicas):
            worker_name = f"{cluster_name}-worker-{i}"
            services[worker_name] = ComposeService(
                container_name=worker_name,
                image=image,
                ports=[f"{ports_start + i}:{ports_start + i}"],
                volumes=["flock-data:/var/flock"],
                networks=["flock-mesh"],
                environment={"FLOCK_ROLE": "worker", "FLOCK_NODE_ID": worker_name},
                depends_on={coord_name: ComposeDependsOn(condition="service_started")},
                restart="always",
            )

        return ComposeProject(services=services, networks=networks, volumes=volumes)


class ComposeValidationResult(BaseModel):
    """Validation report mapping service inconsistencies."""
    is_valid: bool
    errors: List[str] = Field(default_factory=list)

    model_config = {"frozen": True}


class ComposeValidator:
    """Compose specifications structural validator."""

    @staticmethod
    def validate_project(project: ComposeProject) -> ComposeValidationResult:
        """Assert unique service names, valid dependency references, and port format syntax."""
        errors: List[str] = []
        services = project.services

        for name, service in services.items():
            # 1. Dependency checks
            for dep_name in service.depends_on.keys():
                if dep_name not in services:
                    errors.append(f"Service '{name}' depends on missing service '{dep_name}'")

            # 2. Port mapping check
            for p in service.ports:
                if ":" not in p:
                    errors.append(f"Invalid port mapping: '{p}' in service '{name}'")

        return ComposeValidationResult(
            is_valid=len(errors) == 0,
            errors=errors
        )
