"""CLI Subsystem Models."""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class CommandDefinition(BaseModel):
    """Represents a registered CLI command parameter template."""
    name: str
    description: str
    required_permissions: List[str] = Field(default_factory=list)

    model_config = {
        "frozen": True
    }


class CommandRequest(BaseModel):
    """Represents a submitted CLI execution command."""
    command_line: str

    model_config = {
        "frozen": True
    }


class CommandResponse(BaseModel):
    """Represents returned data output from a command execution."""
    success: bool
    output: str
    error: Optional[str] = None

    model_config = {
        "frozen": True
    }


class CommandContext(BaseModel):
    """Represents active state settings passed to executors."""
    active_profile: str
    active_context: str

    model_config = {
        "frozen": True
    }


class ExecutionResult(BaseModel):
    """Represents output metrics for completed runs."""
    exit_code: int
    data: Dict[str, Any] = Field(default_factory=dict)

    model_config = {
        "frozen": True
    }


class ExecutionProgress(BaseModel):
    """Represents updates sent back during long-running tasks."""
    percent_completed: float
    message: str

    model_config = {
        "frozen": True
    }


class SessionMetadata(BaseModel):
    """Represents session identifiers and token lifetimes."""
    session_id: str
    token: str
    expires_at: float

    model_config = {
        "frozen": True
    }


class ProfileDefinition(BaseModel):
    """Represents user credentials configurations."""
    username: str
    roles: List[str] = Field(default_factory=list)

    model_config = {
        "frozen": True
    }


class ConfigurationModel(BaseModel):
    """Represents global platform configuration variables."""
    active_cluster: str
    contexts: List[str] = Field(default_factory=list)

    model_config = {
        "frozen": True
    }


class CompletionCandidate(BaseModel):
    """Represents matches generated by auto-completion engines."""
    value: str
    display: str

    model_config = {
        "frozen": True
    }


class CommandHistory(BaseModel):
    """Represents historical commands executions list."""
    history_lines: List[str] = Field(default_factory=list)

    model_config = {
        "frozen": True
    }


class OutputFormat(BaseModel):
    """Represents target layout format designations."""
    format_type: str  # 'table', 'json', 'yaml'

    model_config = {
        "frozen": True
    }


class ClusterContext(BaseModel):
    """Represents active host endpoints address configs."""
    context_name: str
    endpoint: str

    model_config = {
        "frozen": True
    }


class AuthenticationContext(BaseModel):
    """Represents credentials verified states."""
    authenticated: bool
    identity: str

    model_config = {
        "frozen": True
    }


class CliMetrics(BaseModel):
    """Represents metrics collected from CLI commands run counts."""
    executed_commands_count: int

    model_config = {
        "frozen": True
    }


class CliStatistics(BaseModel):
    """Represents statistics calculated from runtime latency averages."""
    average_latency_ms: float

    model_config = {
        "frozen": True
    }
