"""Structured telemetry exporters (JSON & Prometheus format)."""

from __future__ import annotations

import json
from typing import List

from flock.observability.exceptions import ExporterError
from flock.observability.models import MetricType, MetricValue


class TelemetryExporter:
    """Formats and exports telemetry metrics in JSON or Prometheus format."""

    def __init__(self) -> None:
        pass

    def export_json(self, metrics: List[MetricValue]) -> str:
        """Serialize list of MetricValue points into structured JSON string."""
        try:
            data = [m.model_dump() for m in metrics]
            return json.dumps(data, indent=2)
        except Exception as exc:
            raise ExporterError(f"JSON export failed: {exc}") from exc

    def export_prometheus(self, metrics: List[MetricValue]) -> str:
        """Convert metric list into Prometheus exposition format text."""
        lines: List[str] = []
        for m in metrics:
            # Format label brackets
            label_str = ""
            if m.labels:
                labels_formatted = [f'{k}="{v}"' for k, v in m.labels.items()]
                label_str = "{" + "," + ",".join(labels_formatted) + "}"
                # Clean prefix commas if any
                label_str = label_str.replace("{,", "{")

            # Escape name for prometheus standards
            prom_name = m.name.replace(".", "_")

            # HELP & TYPE annotation blocks
            lines.append(f"# HELP {prom_name} Metric generated by Flock framework")
            lines.append(f"# TYPE {prom_name} {m.type.value.lower()}")
            lines.append(f"{prom_name}{label_str} {m.value}")

        return "\n".join(lines) + "\n"
